name: 'Type of Web Bundlephobia PR stats'
description: 'Compare bundle size for Pull Requests'
inputs:
  path:
    description: 'Directory against which the build will be compared'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  color: green
  icon: 'bar-chart-2'
